//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int MaNV { get; set; }
        public string TenNhanVien { get; set; }
        public string DiaChiNV { get; set; }
        public string DienThoaiNV { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
