//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANTRIVIEN
    {
        public int MaQuanTri { get; set; }
        public string TenQuanTri { get; set; }
        public string GioiTinhQTV { get; set; }
        public System.DateTime NgaySinhQTV { get; set; }
        public string TenDNQTV { get; set; }
        public string MatKhauDNQTV { get; set; }
        public string DiaChiQTV { get; set; }
        public string DienThoaiQTV { get; set; }
        public string EmailQTV { get; set; }
        public Nullable<int> QuyenQTV { get; set; }
    }
}
